### ISSUE TITLE
'columns' isn't set in the Request

### ISSUE THREAD

**Issue by Globulopolis** [halfdan/IPv6Usage#19]
I got an error on Ipv6 Evolution report:
> The parameter 'columns' isn't set in the Request, and a default value wasn't provided.
Any suggestion?

**Comment by tuxmaster** [comment]
To show the error, here an screen shot. (of the German version)
![bildschirmfoto von 2015-04-01 11 31 09](https://cloud.githubusercontent.com/assets/6240474/6938338/fea51b2e-d862-11e4-8436-00219eae4776.png)

**Comment by fritteli** [comment]
I'm facing the same issue. Any chance this will be fixed soon? If I knew how to develop Piwik plugins, I'd offer my help, but unfortunately I have no experience with that.

**Comment by fritteli** [comment]
Same situation with plugin version 0.7.1, Piwik 2.14.0, PHP 5.6.

**Comment by SWefels** [comment]
Same issue here.
When i add the "columns" into the request, i get a fatal error from Piwik:

 
A fatal error occurred

The following error just broke Piwik (v2.14.3):

Call to a member function getColumns() on a non-object
in
/var/www/piwik/piwik/core/Plugin/Visualization.php line 339

----
Running Apache2.4.10 + PHP 5.5.18 + Piwik 2.14.3 with IPv6Usage v0.7.1

**Comment by halfdan** [comment]
Fixed in 0.8.0 thanks to @foscarini
