### ISSUE TITLE
Problems when running under PHP 5.6(?)

### ISSUE THREAD

**Issue by thosch66** [halfdan/IPv6Usage#20]
I migarted my webspace to PHP 5.6. After the migration Piwik stopped countig the page hits.

I found masses of this error-messages in the PHP-error-logs:

[Sun Apr 26 19:27:40.010786 2015] [:error] [pid 5715] [client 2001:bf0:c000:a::1:124:55170] PHP Fatal error:  Call to undefined method Piwik\\IP::isIPv4() in /xxx/xxx/xxx/thoschworks.de/piwik/plugins/IPv6Usage/IPv6Usage.php on line 96, referer: http://thoschworks.de/blog/

After I deactivated IPv6Usage Piwik counts teh hits again.

Regards

Thomas

**Comment by halfdan** [comment]
Should be fixed by the most recent release. The method was removed in an update to Piwik.

**Comment by thosch66** [comment]
After the update it works (again). Thanks.
