### ISSUE TITLE
Page "IPv6 Usage" show only 0 values

### ISSUE THREAD

**Issue by sinky** [halfdan/IPv6Usage#22]
On the page "IPv6 Usage" only 0 values are displayed. However, the widget displays values.

**Comment by fritteli** [comment]
I second that. Piwik 2.14.1, IPv6Usage 0.7.1, PHP 5.6.10.

**Comment by sinky** [comment]
Piwik 2.14.1
IPv6Usage (v0.7.1)
PHP 5.5.5

**Comment by jangrewe** [comment]
+1
Piwik 2.14.3
PHP 5.6.7-1

**Comment by Erulezz** [comment]
+1 Also in 2.15.0

Also when i try to add the Evolution Widget i get this error:

Error: The parameter 'columns' isn't set in the Request, and a default value wasn't provided.

The other widget is working.

**Comment by halfdan** [comment]
Fixed in 0.8.0 thanks to @foscarini
