### ISSUE TITLE
Not compatible with Piwik 3

### ISSUE THREAD

**Issue by florianbeer** [halfdan/IPv6Usage#26]
The Plugin is installed, no errors, but nothing shows up in the UI.

**Comment by fritteli** [comment]
This is the only reason that prevents me from updating Piwik to version 3. Looks like migrating a plugin from Piwik 2 to Piwik 3 requires some work ...
https://developer.piwik.org/guides/migrate-piwik-2-to-3

**Comment by johsin18** [comment]
I have started porting this plugin to Piwik 3 on this branch:
https://github.com/johsin18/IPv6Usage/tree/piwik3
It works again in principle, but deserves quite some polishing (e.g. graph labels, limiting the selection to visits for the pie chart, translations in general) still.  Help is appreciated.
I had to change much more than mentioned in that migration guide.  Many used components had been deprecated for former 2.x versions already, and were finally removed for Piwik 3.
